checksumBehavior: ignore

packageExtensions:
  '@typescript-eslint/utils@*':
    dependencies:
      eslint: '8'

  'eslint-config-next@*':
    dependencies:
      next: '*'

  'next@^15':
    dependencies:
      nextra: '4.0.0'
      nextra-theme-docs: '4.0.0'

  'langium@*':
    dependencies:
      '@chevrotain/regexp-to-ast': '11.0.3'
      vscode-languageserver: '9.0.1'
      vscode-languageserver-protocol: '3.17.5'
      vscode-languageserver-types: '3.17.5'
      vscode-jsonrpc: '8.2.0'

  'acorn-jsx@*':
    dependencies:
      acorn: '*'

  '@aztec/foundation@0.55.1':
    dependencies:
      'tslib': '^2.6.3'

  '@aztec/circuit-types@0.55.1':
    dependencies:
      'viem': '^2.20.0'

  '@storybook/nextjs@8.5.6':
    dependencies:
      'next': '*'
      'webpack': '*'

  'postcss-loader@*':
    dependencies:
      '@tailwindcss/postcss': '*'
