
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  L1EventPayload,
  loadContractArtifact,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  type Wallet,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import HistoricDataFeedStoreContractArtifactJson from '../../target/historic_data_feed_store-HistoricDataFeedStore.json' assert { type: 'json' };
export const HistoricDataFeedStoreContractArtifact = loadContractArtifact(HistoricDataFeedStoreContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract HistoricDataFeedStore;
 */
export class HistoricDataFeedStoreContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, HistoricDataFeedStoreContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, HistoricDataFeedStoreContract.artifact, wallet) as Promise<HistoricDataFeedStoreContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<HistoricDataFeedStoreContract>(Fr.ZERO, wallet, HistoricDataFeedStoreContractArtifact, HistoricDataFeedStoreContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeysHash(publicKeysHash: Fr, wallet: Wallet, ) {
    return new DeployMethod<HistoricDataFeedStoreContract>(publicKeysHash, wallet, HistoricDataFeedStoreContractArtifact, HistoricDataFeedStoreContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof HistoricDataFeedStoreContract['methods']>(
    opts: { publicKeysHash?: Fr; method?: M; wallet: Wallet },
    ...args: Parameters<HistoricDataFeedStoreContract['methods'][M]>
  ) {
    return new DeployMethod<HistoricDataFeedStoreContract>(
      opts.publicKeysHash ?? Fr.ZERO,
      opts.wallet,
      HistoricDataFeedStoreContractArtifact,
      HistoricDataFeedStoreContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return HistoricDataFeedStoreContractArtifact;
  }
  

  public static get storage(): ContractStorageLayout<'historic_data_feeds' | 'counters' | 'owner'> {
      return {
        historic_data_feeds: {
      slot: new Fr(1n),
    },
counters: {
      slot: new Fr(2n),
    },
owner: {
      slot: new Fr(3n),
    }
      } as ContractStorageLayout<'historic_data_feeds' | 'counters' | 'owner'>;
    }
    

  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, serialized_note: array) */
    compute_note_hash_and_optionally_a_nullifier: ((contract_address: AztecAddressLike, nonce: FieldLike, storage_slot: FieldLike, note_type_id: FieldLike, compute_nullifier: boolean, serialized_note: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor() */
    constructor: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_data_feed(key: field) */
    get_data_feed: ((key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_feed_at_counter(key: field, counter: field) */
    get_feed_at_counter: ((key: FieldLike, counter: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_latest_counter(key: field) */
    get_latest_counter: ((key: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_feeds(keys: array, input_values: array, length: integer) */
    set_feeds: ((keys: FieldLike[], input_values: (bigint | number)[], length: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
