name: Trigger Downstream Flake Update on Push to Main

on:
  pull_request:
    types: [opened, reopened]

jobs:
  trigger-downstream-repo:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - downstream-repo: 'galin-s/test'
    steps:
      - uses: tibdex/github-app-token@v2.1.0
        id: generate-token
        with:
          app_id: ${{ secrets.NIX_FLAKE_UPDATE_PR_BOT_APP_ID }}
          private_key: ${{ secrets.NIX_FLAKE_UPDATE_PR_BOT_APP_PRIVATE_KEY }}

      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          merge-method: rebase
          do-not-merge-labels: never-merge
          required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
          review: ${{ github.event.inputs.review }}
          dry-run: true
