name: Test Auto Merge

on:
  pull_request:
    types: [opened, reopened]

jobs:
  trigger-downstream-repo:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - downstream-repo: 'galin-s/test'
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.GALIN_TOKEN }}
          merge-method: rebase
          do-not-merge-labels: never-merge
          required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
          review: ${{ github.event.inputs.review }}
          dry-run: true
